---
apiVersion: v1
kind: Namespace
metadata:
  name: ldap
  labels:
    name: ldap
    project: ldap
    access: internal
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: namespace
  namespace: ldap
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
